Repository AY2122S1-CS2103T-W13-2/tp, pull requests merged in 2021-09, with the labels that each got.

#30 Update DG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/zhou-jiahao-1998.png
Labels: priority.High

#36 Update UG markdown syntax and find section
  docs/UserGuide.md
Labels: type.Chore, priority.High

#38 Fix inconsistencies in user guide
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.VeryLow

#45 Update readme
  README.md
Labels: type.Chore, priority.High
