Repository AY2122S1-CS2103T-W13-2/tp, pull requests merged in 2021-11, with the labels that each got.

#227 Improve find and edit commands
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/ContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Enhancement, priority.Medium

#229 Fix #130
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/LoginScreen.java
  src/main/java/seedu/address/ui/SetUpScreen.java
Labels: type.Bug

#232 Improve GUI
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/SettingsWindow.fxml
Labels: priority.High

#234 UG Updates for PED
  docs/UserGuide.md
  docs/images/helpWindow.gif
  docs/images/helpWindow.png
  docs/images/select.gif
  docs/images/select.png
  docs/images/unselect.gif
Labels: priority.High, docs

#236 Jiahao/change password bug fix
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
Labels: type.Bug

#237 Separate password validity check out
  src/main/java/seedu/address/commons/util/PasswordUtil.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/main/java/seedu/address/ui/LoginScreen.java
  src/main/java/seedu/address/ui/SetUpScreen.java
  src/test/java/seedu/address/commons/util/PasswordUtilTest.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
Labels: type.Enhancement, severity.Low

#246 Fix bugs found
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: type.Bug, severity.Medium

#244 Improve file write error message during export command
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Bug, severity.Low

#248 Jiahao/password long form
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
Labels: type.Enhancement, priority.Medium, docs

#249 Add PPP
  docs/team/anonymxtrix.md
Labels: type.Chore, priority.High, docs

#247 Jiahao/docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FlowChangePassword.png
  docs/images/FlowLogIn.png
  docs/images/FlowSetUpPassword.png
  docs/images/SetUpPassword.png
  docs/images/setUpPassword.png
  docs/team/zhou-jiahao-1998.md
  src/main/java/seedu/address/commons/util/PasswordUtil.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/test/java/seedu/address/commons/util/PasswordUtilTest.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
Labels: docs

#253 Add PPP
  docs/team/zhenghanlee.md
Labels: type.Chore, priority.High, docs

#252 Fix set up non ASCII character bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/LoginScreen.java
  src/main/java/seedu/address/ui/SetUpScreen.java
Labels: type.Bug, priority.High

#255 Jiahao/code quality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/PasswordUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/ui/LoginScreen.java
  src/main/java/seedu/address/ui/SetUpScreen.java
  src/test/java/seedu/address/encryption/EncryptionTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Enhancement

#256 Add truncation to long tags
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Bug, severity.Low

#257 Remove unnecessary information from person toString
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Bug, severity.Low

#260 Add enhancements and project management sections to PPP
  docs/team/anonymxtrix.md
Labels: type.Chore, priority.High, docs

#259 Add graphical user interface section in user guide
  docs/UserGuide.md
  docs/images/GraphicalUserInterface.png
Labels: type.Bug, priority.High, docs

#262 Add PasswordCommand sequence diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PasswordCommandSequenceDiagram.puml
  docs/images/PasswordCommandSequenceDiagram.png
  docs/team/zhou-jiahao-1998.md
Labels: docs
